name: publish-plugin

on:
  workflow_dispatch:

jobs:
  publish-plugin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Bump version in manifest.json
        run: bash ./bump-version.sh

      - name: Publish to Windy
        uses: windycom/publish-plugin-action@v1
        with:
          api-key: ${{ secrets.WINDY_API_KEY }}
