name: publish-plugin

on:
  workflow_dispatch:

jobs:
  publish-plugin:
    runs-on: ubuntu-latest
    env:
      WINDY_API_KEY: ${{ secrets.WINDY_API_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Create plugin archive and publish
        run: |
          cd dist
          echo "Creating plugin archive..."
          tar cf ../plugin.tar .

          echo "Publishing plugin..."
          curl -s --fail-with-body -XPOST 'https://node.windy.com/plugins/v1.0/upload' \
            -H "x-windy-api-key: $WINDY_API_KEY" \
            -F "plugin_archive=@../plugin.tar"
